spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/journaldb
      database: journaldb

  redis:
    host: localhost
    port: 6379
    password: ""
    ssl: false

server:
  port: 8080
